name: "Javascript Backend Boilerplate Generator"
author: "Ohioze Alex Omiunu"
description: "Generates a boilerplate for your project"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
   icon: "folder"
   color: "red"
inputs:
    email:
      description: The commiter's email address
      required: true
      default: #{{github.actor}}@localhost
    name:
      description: The committer's name
      required: true
      default: ${{github.actor}}
